//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsw2026Tpi.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dsw2026Tpi.CrossCutting.Resources.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El horario seleccionado ya fue reservado.
        /// </summary>
        public static string APPOINTMENT_CONFLICT {
            get {
                return ResourceManager.GetString("APPOINTMENT_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato de fecha debe ser YYYY-MM-DD.
        /// </summary>
        public static string APPOINTMENT_DATE_INVALID {
            get {
                return ResourceManager.GetString("APPOINTMENT_DATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El horario seleccionado no pertenece al médico indicado.
        /// </summary>
        public static string APPOINTMENT_DOCTOR_MISMATCH {
            get {
                return ResourceManager.GetString("APPOINTMENT_DOCTOR_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede operar sobre turnos de otro paciente.
        /// </summary>
        public static string APPOINTMENT_FORBIDDEN {
            get {
                return ResourceManager.GetString("APPOINTMENT_FORBIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden reservar turnos en fechas u horarios pasados.
        /// </summary>
        public static string APPOINTMENT_IN_THE_PAST {
            get {
                return ResourceManager.GetString("APPOINTMENT_IN_THE_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se pueden cancelar turnos reservados.
        /// </summary>
        public static string APPOINTMENT_NOT_CANCELLABLE {
            get {
                return ResourceManager.GetString("APPOINTMENT_NOT_CANCELLABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El turno indicado no existe.
        /// </summary>
        public static string APPOINTMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("APPOINTMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El motivo debe tener al menos 5 caracteres.
        /// </summary>
        public static string APPOINTMENT_REASON_LENGTH {
            get {
                return ResourceManager.GetString("APPOINTMENT_REASON_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El horario indicado no existe.
        /// </summary>
        public static string APPOINTMENT_SLOT_NOT_FOUND {
            get {
                return ResourceManager.GetString("APPOINTMENT_SLOT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El horario seleccionado no está disponible.
        /// </summary>
        public static string APPOINTMENT_SLOT_UNAVAILABLE {
            get {
                return ResourceManager.GetString("APPOINTMENT_SLOT_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos.
        /// </summary>
        public static string AUTHENTICATION_FAILED {
            get {
                return ResourceManager.GetString("AUTHENTICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requieren permisos para la operación solicitada.
        /// </summary>
        public static string AUTHORIZATION_FAILED {
            get {
                return ResourceManager.GetString("AUTHORIZATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar al menos un día de atención.
        /// </summary>
        public static string AVAILABILITY_DAYS_REQUIRED {
            get {
                return ResourceManager.GetString("AVAILABILITY_DAYS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede reemplazar el mes: hay turnos reservados.
        /// </summary>
        public static string AVAILABILITY_HAS_BOOKED_APPOINTMENTS {
            get {
                return ResourceManager.GetString("AVAILABILITY_HAS_BOOKED_APPOINTMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El día indicado no es un día válido de la semana.
        /// </summary>
        public static string AVAILABILITY_INVALID_DAY {
            get {
                return ResourceManager.GetString("AVAILABILITY_INVALID_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La hora de inicio debe ser anterior a la de fin.
        /// </summary>
        public static string AVAILABILITY_INVALID_RANGE {
            get {
                return ResourceManager.GetString("AVAILABILITY_INVALID_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato de hora debe ser HH:mm.
        /// </summary>
        public static string AVAILABILITY_INVALID_TIME {
            get {
                return ResourceManager.GetString("AVAILABILITY_INVALID_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los horarios deben empezar y terminar en bloques de 30 minutos.
        /// </summary>
        public static string AVAILABILITY_NOT_ALIGNED {
            get {
                return ResourceManager.GetString("AVAILABILITY_NOT_ALIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El horario se superpone con otra disponibilidad del médico.
        /// </summary>
        public static string AVAILABILITY_OVERLAP {
            get {
                return ResourceManager.GetString("AVAILABILITY_OVERLAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe tener entre 3 y 100 caracteres.
        /// </summary>
        public static string DOCTOR_NAME_LENGTH {
            get {
                return ResourceManager.GetString("DOCTOR_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El médico indicado no existe.
        /// </summary>
        public static string DOCTOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("DOCTOR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La especialidad indicada no existe.
        /// </summary>
        public static string DOCTOR_SPECIALTY_NOT_FOUND {
            get {
                return ResourceManager.GetString("DOCTOR_SPECIALTY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entidad {0} no se encontró.
        /// </summary>
        public static string ENTITY_NOTFOUND {
            get {
                return ResourceManager.GetString("ENTITY_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI debe tener entre 7 y 10 dígitos.
        /// </summary>
        public static string PATIENT_DNI_INVALID {
            get {
                return ResourceManager.GetString("PATIENT_DNI_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un paciente con ese DNI.
        /// </summary>
        public static string PATIENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PATIENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al registrar el usuario.
        /// </summary>
        public static string REGISTER_USER_CONFLICT {
            get {
                return ResourceManager.GetString("REGISTER_USER_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de registración de usuario no válidos.
        /// </summary>
        public static string REGISTER_USER_INVALID {
            get {
                return ResourceManager.GetString("REGISTER_USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción debe tener entre 10 y 100 caracteres.
        /// </summary>
        public static string SPECIALTY_DESCRIPTION_LENGTH {
            get {
                return ResourceManager.GetString("SPECIALTY_DESCRIPTION_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una especialidad con ese nombre.
        /// </summary>
        public static string SPECIALTY_DUPLICATED {
            get {
                return ResourceManager.GetString("SPECIALTY_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe tener entre 3 y 100 caracteres.
        /// </summary>
        public static string SPECIALTY_NAME_LENGTH {
            get {
                return ResourceManager.GetString("SPECIALTY_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es obligatorio.
        /// </summary>
        public static string SPECIALTY_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("SPECIALTY_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La especialidad indicada no existe.
        /// </summary>
        public static string SPECIALTY_NOT_FOUND {
            get {
                return ResourceManager.GetString("SPECIALTY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error no controlado.
        /// </summary>
        public static string UNHANDLED_ERROR {
            get {
                return ResourceManager.GetString("UNHANDLED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro ya existe.
        /// </summary>
        public static string UNIQUE_CONSTRAINT_VIOLATION {
            get {
                return ResourceManager.GetString("UNIQUE_CONSTRAINT_VIOLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno o más errores de validación ocurrieron.
        /// </summary>
        public static string VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Demasiadas solicitudes. Intente nuevamente en unos instantes.
        /// </summary>
        public static string RATE_LIMIT_EXCEEDED {
            get {
                return ResourceManager.GetString("RATE_LIMIT_EXCEEDED", resourceCulture);
            }
        }
    }
}
